### ISSUE TITLE
Handle topic timeout w/URI-query option and 4.04 and data staleness with max-age

### ISSUE THREAD

**Issue by mjkoster** [core-wg/coap-pubsub#34]
As per the CoRE interim discussion, we would like to support topic lifetime setting using a URI-query option (e.g. "tlt") on topic creation. If the topic isn't published to before the lifetime expires, the topic is removed, resulting in a 4.04 response to new SUBSCRIBE or READ requests, and the broker closes outstanding observes with a 4.04. Publishing to the topic resets the lifetime counter.

Max-age will be used for data staleness. We suggest to provide the same feature to subscribing clients that a cache would use. One issue with Max-age is that it only applies to responses, and we need to convey the data lifetime on publish. We could use a uri-query option (e.g. "dlt") or a new header option for publish-max-age. Without this, the default Max-Age of 60 seconds would be required. For READ and SUBSCRIBE responses it will be (60 seconds - seconds since publish).

**Comment by jaimejim** [comment]
This is now handled by https://core-wg.github.io/coap-pubsub/ps-rev/draft-ietf-core-coap-pubsub.html#name-topic-properties: expiration_date

Closing the issue.
